import Head from 'next/head';
import Header from '../components/Header';
import Card from '../components/Card';

const style = {
  wrapper: `min-h-screen flex flex-col bg-[#222229] overflow-hidden`,
  cardsContainer: `flex flex-col items-center justify-center flex-1`,
};

export default function Home() {
  return (
    <div className={style.wrapper}>
      <Head>
        <title>Tinder BlockChain Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className={style.cardsContainer}>
        <Card />
      </div>
    </div>
  );
}
